export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOAD_USER = 'LOAD_USER';
export const USER_LOADED = 'USER_LOADED';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
