export const GET_CURRENT_PROFILE_START = 'GET_CURRENT_PROFILE_START';
export const GET_CURRENT_PROFILE_SUCCESS = 'GET_CURRENT_PROFILE_SUCCESS';
export const GET_CURRENT_PROFILE_FAILED = 'GET_CURRENT_PROFILE_FAILED';