export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CREATE_OR_UPDATE_PROFILE_START = 'CREATE_OR_UPDATE_PROFILE_START';
export const GET_CURRENT_PROFILE_START = 'GET_CURRENT_PROFILE_START';
export const GET_CURRENT_PROFILE_SUCCESS = 'GET_CURRENT_PROFILE_SUCCESS';
export const GET_CURRENT_PROFILE_FAILED = 'GET_CURRENT_PROFILE_FAILED';